auth.datasource.url=jdbc:postgresql://localhost:5432/auth_db
auth.datasource.username=postgres
auth.datasource.password=123

booking.datasource.url=jdbc:postgresql://localhost:5432/booking_db
booking.datasource.username=postgres
booking.datasource.password=123

spring.flyway.enabled=false

