# auth_db
auth.datasource.url=jdbc:postgresql://localhost:5432/auth_db
auth.datasource.username=postgres
auth.datasource.password=123

#booking_db
booking.datasource.url=jdbc:postgresql://localhost:5432/booking_db
booking.datasource.username=postgres
booking.datasource.password=123

#flyway
spring.flyway.enabled=false

#JWT
# openssl rand -base64 32 | tr '+/' '-_' | tr -d '='
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=15m

